company = ['sega', 'nintendo', 'atari', 'nec', 'snk', 'mattel electronics']

consoles = [['sega', 'Genesis'],
            ['sega', 'Master System'],
            ['nintendo', 'NES'],
            ['nintendo', 'SNES'],
            ['atari', '2600'],
            ['nec', 'TurboGrafx-16'],
            ['snk', 'Neo Geo'],
            ['mattel electronics', 'Intellivision']]

games = [['Genesis', 'Sonic the Hedghog 2', 'Action / Platformer'],
         ['Genesis', 'Quackshot: Starring Donald Duck', 'Action / Platformer'],
         ['Genesis', 'Streets of Rage 2', 'Beat \'em-up'],
         ['Genesis', 'Flashback', 'Action / Adventure'],
         ['Genesis', 'Dr Robotnik\'s Mean Bean Machine', 'Puzzle'],
         ['Genesis', 'Shining Force 2', 'RPG'],
         ['NES', 'The Legend of Zelda', 'RPG'],
         ['NES', 'Tetris', 'Puzzle'],
         ['NES', 'Super Mario Bros 3', 'Action / Platformer'],
         ['NES', 'Metroid', 'Action / Adventure'],
         ['NES', 'Contra', 'Run \'n Gun'],
         ['NES', 'Excitebike', 'Racing'],
         ['2600', 'Space Invaders', 'Shoot \'em-up'],
         ['2600', 'Pac Man', 'Arcade'],
         ['2600', 'Pitfall', 'Action / Platformer'],
         ['2600', 'Missile Command', 'Arcade'],
         ['2600', 'Adventure', 'Action / Adventure'],
         ['2600', 'Frogger', 'Arcade'],
         ['TurboGrafx-16', 'Ninja Spirit', 'Action / Platformer'],
         ['TurboGrafx-16', 'Splatterhouse', 'Beat \'em-up'],
         ['TurboGrafx-16', 'Cadash', 'RPG'],
         ['TurboGrafx-16', 'Soldier Blade', 'Shoot \'em-up'],
         ['TurboGrafx-16', 'Bonk\'s Revenge', 'Action / Platformer'],
         ['TurboGrafx-16', 'Parasol Stars', 'Platformer'],
         ['Neo Geo', 'Samurai Showdown 2', 'Beat \'em-up'],
         ['Neo Geo', 'Metal Slug', 'Run \'n Gun'],
         ['Neo Geo', 'Blazing Star', 'Shoot \'em-up'],
         ['Neo Geo', 'King of Fighters', 'Beat \'em-up'],
         ['Neo Geo', 'Neo Turf Masters', 'Sports'],
         ['Neo Geo', 'Pustar', 'Shoot \'em-up'],
         ['SNES', 'Donkey Kong Country 2', 'Action / Platformer'],
         ['SNES', 'The Legend of Zelda: A Link to the Past', 'RPG'],
         ['SNES', 'Super Mario Kart', 'Racing'],
         ['SNES', 'Street Fighter 2', 'Beat \'em-up'],
         ['SNES', 'Super Mario World', 'Action / Platformer'],
         ['SNES', 'Earthbound', 'RPG'],
         ['Intellivision', 'Donkey Kong Jr', 'Platformer'],
         ['Intellivision', 'Burger Time', 'Platformer'],
         ['Intellivision', 'Bump \'n Jump', 'Action / Racing'],
         ['Intellivision', 'Defender', 'Shoot \'em-up'],
         ['Intellivision', 'Astro Smash', 'Shoot \'em-up'],
         ['Intellivision', 'Advanced Dungeons and Dragons', 'RPG'],
         ['Master System', 'Psycho Fox', 'Action / Platformer'],
         ['Master System', 'Alex Kidd in Miracle World', 'Action / Platformer'],
         ['Master System', 'Sonic Chaos', 'Action / Platformer'],
         ['Master System', 'Shinobi', 'Arcade'],
         ['Master System', 'Wonderboy in Monsterland', 'Action / Platformer'],
         ['Master System', 'Ys 1: The Vanished Omens', 'RPG']]