consoles = ['sega', 'nintendo', 'atari', 'nEC', 'sNK', 'mattel Electronics']

games = [['sega', 'Genesis', 'Sonic the Hedghog 2', 'Action / Platformer'],
         ['sega', 'Genesis', 'Quackshot: Starring Donald Duck', 'Action / Platformer'],
         ['sega', 'Genesis', 'Streets of Rage 2', 'Beat \'em-up'],
         ['sega', 'Genesis', 'Flashback', 'Action / Adventure'],
         ['sega', 'Genesis', 'Dr Robotnik\'s Mean Bean Machine', 'Puzzle'],
         ['sega', 'Genesis', 'Shining Force 2', 'RPG'],
         ['nintendo', 'NES', 'The Legend of Zelda', 'RPG'],
         ['nintendo', 'NES', 'Tetris', 'Puzzle'],
         ['nintendo', 'NES', 'Super Mario Bros 3', 'Action / Platformer'],
         ['nintendo', 'NES', 'Metroid', 'Action / Adventure'],
         ['nintendo', 'NES', 'Contra', 'Run \'n Gun'],
         ['nintendo', 'NES', 'Excitebike', 'Racing'],
         ['atari', '2600', 'Space Invaders', 'Shoot \'em-up'],
         ['atari', '2600', 'Pac Man', 'Arcade'],
         ['atari', '2600', 'Pitfall', 'Action / Platformer'],
         ['atari', '2600', 'Missile Command', 'Arcade'],
         ['atari', '2600', 'Adventure', 'Action / Adventure'],
         ['atari', '2600', 'Frogger', 'Arcade'],
         ['nEC', 'TurboGrafx-16', 'Ninja Spirit', 'Action / Platformer'],
         ['nEC', 'TurboGrafx-16', 'Splatterhouse', 'Beat \'em-up'],
         ['nEC', 'TurboGrafx-16', 'Cadash', 'RPG'],
         ['nEC', 'TurboGrafx-16', 'Soldier Blade', 'Shoot \'em-up'],
         ['nEC', 'TurboGrafx-16', 'Bonk\'s Revenge', 'Action / Platformer'],
         ['nEC', 'TurboGrafx-16', 'Parasol Stars', 'Platformer'],
         ['sNK', 'Neo Geo', 'Samurai Showdown 2', 'Beat \'em-up'],
         ['sNK', 'Neo Geo', 'Metal Slug', 'Run \'n Gun'],
         ['sNK', 'Neo Geo', 'Blazing Star', 'Shoot \'em-up'],
         ['sNK', 'Neo Geo', 'King of Fighters', 'Beat \'em-up'],
         ['sNK', 'Neo Geo', 'Neo Turf Masters', 'Sports'],
         ['sNK', 'Neo Geo', 'Pustar', 'Shoot \'em-up'],
         ['nintendo', 'SNES', 'Donkey Kong Country 2', 'Action / Platformer'],
         ['nintendo', 'SNES', 'The Legend of Zelda: A Link to the Past', 'RPG'],
         ['nintendo', 'SNES', 'Super Mario Kart', 'Racing'],
         ['nintendo', 'SNES', 'Street Fighter 2', 'Beat \'em-up'],
         ['nintendo', 'SNES', 'Super Mario World', 'Action / Platformer'],
         ['nintendo', 'SNES', 'Earthbound', 'RPG'],
         ['mattel Electronics', 'Intellivision', 'Donkey Kong Jr', 'Platformer'],
         ['mattel Electronics', 'Intellivision', 'Burger Time', 'Platformer'],
         ['mattel Electronics', 'Intellivision', 'Bump \'n Jump', 'Action / Racing'],
         ['mattel Electronics', 'Intellivision', 'Defender', 'Shoot \'em-up'],
         ['mattel Electronics', 'Intellivision', 'Astro Smash', 'Shoot \'em-up'],
         ['mattel Electronics', 'Intellivision', 'Advanced Dungeons and Dragons', 'RPG'],
         ['sega', 'Master System', 'Psycho Fox', 'Action / Platformer'],
         ['sega', 'Master System', 'Alex Kidd in Miracle World', 'Action / Platformer'],
         ['sega', 'Master System', 'Sonic Chaos', 'Action / Platformer'],
         ['sega', 'Master System', 'Shinobi', 'Arcade'],
         ['sega', 'Master System', 'Wonderboy in Monsterland', 'Action / Platformer'],
         ['sega', 'Master System', 'Ys 1: The Vanished Omens', 'RPG']]